@startuml Use cases
left to right direction

:Administrator:
:LineStopper:
:Support:
:Machine:
:Operator:
:QA:

Rectangle {
    usecase (MoveLogfileToBackup)
    usecase (CreatePanelFromLogfile)
    usecase (SendPanelToNextStation)
    
    :Machine: --> (ProcessPanelFromLogfile)
    (ProcessPanelFromLogfile) ..> (MoveLogfileToBackup) : "<include>"
    (ProcessPanelFromLogfile) ..> (CreatePanelFromLogfile) : "<include>"
    (ProcessPanelFromLogfile) ..> (SendPanelToNextStation) : "<include>"  
    (ProcessPanelFromLogfile) <.. (StopLine) : "<extend>"  
    
    (SendPanelToNextStation) <.. (StopMachine) : "<extend>"
    
    :LineStopper: -down-> (StopLine)
    
    (StopLine) ..> (StopMachine) : <include>
    
    (StopMachine) --> :Operator: : Notifies
    (SendPanelToNextStation) --> :Operator: : Notifies
    
    :Support: --> (ReleaseStopMachine)
    :Administrator: --> (UpdateSettings)
    :QA: --> (UpdateQASettings)
}

@enduml