//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string msg_connection_error {
            get {
                return ResourceManager.GetString("msg_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of file.
        /// </summary>
        public static string msg_end_of_file_error {
            get {
                return ResourceManager.GetString("msg_end_of_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string msg_invalid_data_error {
            get {
                return ResourceManager.GetString("msg_invalid_data_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string msg_not_found_error {
            get {
                return ResourceManager.GetString("msg_not_found_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string msg_operation_cancelled_error {
            get {
                return ResourceManager.GetString("msg_operation_cancelled_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning error.
        /// </summary>
        public static string msg_scanning_error {
            get {
                return ResourceManager.GetString("msg_scanning_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string msg_timeout_error {
            get {
                return ResourceManager.GetString("msg_timeout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string msg_unknown_error {
            get {
                return ResourceManager.GetString("msg_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong station.
        /// </summary>
        public static string msg_wrong_station_error {
            get {
                return ResourceManager.GetString("msg_wrong_station_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string txt_all {
            get {
                return ResourceManager.GetString("txt_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string txt_elapsed_time {
            get {
                return ResourceManager.GetString("txt_elapsed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string txt_ok {
            get {
                return ResourceManager.GetString("txt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string txt_repair {
            get {
                return ResourceManager.GetString("txt_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string txt_serial_number {
            get {
                return ResourceManager.GetString("txt_serial_number", resourceCulture);
            }
        }
    }
}
