// <auto-generated />
using Desktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desktop.Data.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20250703201730_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Desktop.Features.Boards.Infrastructure.BoardDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PanelDbModelId");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.Defects.Infrastructure.DefectDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealDefect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationTaskDbModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskDbModelId");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.Logfiles.Infrastructure.LogfileDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logfiles", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.OperationTasks.Infrastructure.OperationTaskDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogfileId");

                    b.HasIndex("OperationDbModelId");

                    b.ToTable("OperationTasks", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.Operations.Infrastructure.OperationDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.Panels.Infrastructure.PanelDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Panels", (string)null);
                });

            modelBuilder.Entity("Desktop.Features.Boards.Infrastructure.BoardDbModel", b =>
                {
                    b.HasOne("Desktop.Features.Panels.Infrastructure.PanelDbModel", null)
                        .WithMany("Boards")
                        .HasForeignKey("PanelDbModelId");
                });

            modelBuilder.Entity("Desktop.Features.Defects.Infrastructure.DefectDbModel", b =>
                {
                    b.HasOne("Desktop.Features.OperationTasks.Infrastructure.OperationTaskDbModel", null)
                        .WithMany("Defects")
                        .HasForeignKey("OperationTaskDbModelId");
                });

            modelBuilder.Entity("Desktop.Features.OperationTasks.Infrastructure.OperationTaskDbModel", b =>
                {
                    b.HasOne("Desktop.Features.Logfiles.Infrastructure.LogfileDbModel", "Logfile")
                        .WithMany()
                        .HasForeignKey("LogfileId");

                    b.HasOne("Desktop.Features.Operations.Infrastructure.OperationDbModel", null)
                        .WithMany("Tasks")
                        .HasForeignKey("OperationDbModelId");

                    b.Navigation("Logfile");
                });

            modelBuilder.Entity("Desktop.Features.Operations.Infrastructure.OperationDbModel", b =>
                {
                    b.HasOne("Desktop.Features.Panels.Infrastructure.PanelDbModel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Desktop.Features.OperationTasks.Infrastructure.OperationTaskDbModel", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Desktop.Features.Operations.Infrastructure.OperationDbModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Desktop.Features.Panels.Infrastructure.PanelDbModel", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
