@startuml Use cases
left to right direction

usecase (ProcessOperation)
usecase (MoveLogfileToBackup)
usecase (AddLogfileToSfc)
usecase (SendUutInConveyor)
usecase (AddUutSerialNumbers)
usecase (LockMachine)
usecase (UnlockMachine)
usecase (AddOperation)

:User: --> (ProcessOperation)
:User: --> (UnlockMachine)
:User: --> (ConfigureSettings)
:User: --> (AddUser)
:User: --> (UpdateUser)
:User: --> (DeleteUser)
:User: --> (SendUutInConveyor)
:User: --> (LockMachine)

:Machine: --> (ProcessOperation)
(ProcessOperation) ..> (MoveLogfileToBackup) : "include"
(ProcessOperation) ..> (AddLogfileToSfc) : "include"
(ProcessOperation) ..> (AddOperation) : "include"

@enduml