@startuml Use cases
left to right direction

usecase (ProcessLogfile)
usecase (UploadLogfileToSfc)
usecase (SendUutInConveyor)
usecase (MoveLogfileToBackup)
usecase (AddUutSerialNumbers)
usecase (LockMachine)
usecase (UnlockMachine)
usecase (ShowOperationResult)
usecase (AddOperation)

:User: --> (ProcessLogfile)
:User: --> (UnlockMachine)
:User: --> (ConfigureSettings)
:User: --> (AddUser)
:User: --> (EditUser)
:User: --> (DeleteUser)

:Machine: --> (ProcessLogfile)
(ProcessLogfile) ..> (UploadLogfileToSfc) : "include"
(ProcessLogfile) ..> (SendUutInConveyor) : "include"
(ProcessLogfile) ..> (MoveLogfileToBackup) : "include"
(ProcessLogfile) ..> (AddUutSerialNumbers) : "include"
(ProcessLogfile) ..> (LockMachine) : "include"
(ProcessLogfile) ..> (ShowOperationResult) : "include"
(ProcessLogfile) ..> (AddOperation) : "include"

@enduml