// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(HermesContext))]
    partial class HermesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PanelDbModelId");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Defects.DefectDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardDbModelId");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Logfiles.LogfileDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logfiles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Operations.OperationDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogfileId");

                    b.HasIndex("PanelDbModelId");

                    b.ToTable("OperationDbModel");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Panels.PanelDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Panels", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Panels.PanelDbModel", null)
                        .WithMany("Boards")
                        .HasForeignKey("PanelDbModelId");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Defects.DefectDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Boards.BoardDbModel", null)
                        .WithMany("Defects")
                        .HasForeignKey("BoardDbModelId");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Operations.OperationDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Logfiles.LogfileDbModel", "Logfile")
                        .WithMany()
                        .HasForeignKey("LogfileId");

                    b.HasOne("Infrastructure.Data.Features.Panels.PanelDbModel", null)
                        .WithMany("Operations")
                        .HasForeignKey("PanelDbModelId");

                    b.Navigation("Logfile");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDbModel", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Panels.PanelDbModel", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
