// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(HermesContext))]
    partial class HermesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PanelDtoId");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Defects.DefectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardDtoId");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Errors.ErrorDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Errors", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Logfiles.LogfileDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logfiles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Operations.OperationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ErrorId");

                    b.HasIndex("LogfileId");

                    b.HasIndex("PanelDtoId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Panels.PanelDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Panels", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDto", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Panels.PanelDto", null)
                        .WithMany("Boards")
                        .HasForeignKey("PanelDtoId");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Defects.DefectDto", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Boards.BoardDto", null)
                        .WithMany("Defects")
                        .HasForeignKey("BoardDtoId");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Operations.OperationDto", b =>
                {
                    b.HasOne("Infrastructure.Data.Features.Errors.ErrorDto", "Error")
                        .WithMany()
                        .HasForeignKey("ErrorId");

                    b.HasOne("Infrastructure.Data.Features.Logfiles.LogfileDto", "Logfile")
                        .WithMany()
                        .HasForeignKey("LogfileId");

                    b.HasOne("Infrastructure.Data.Features.Panels.PanelDto", null)
                        .WithMany("Operations")
                        .HasForeignKey("PanelDtoId");

                    b.Navigation("Error");

                    b.Navigation("Logfile");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Boards.BoardDto", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Infrastructure.Data.Features.Panels.PanelDto", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
