// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Infrastructure.Data.Boards.BoardDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanelDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PanelDbModelId");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Defects.DefectDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealDefect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationTaskDbModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskDbModelId");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Logfiles.LogfileDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logfiles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.OperationTasks.OperationTaskDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogfileId");

                    b.HasIndex("OperationDbModelId");

                    b.ToTable("OperationTasks", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Operations.OperationDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Panels.PanelDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Panels", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Boards.BoardDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Panels.PanelDbModel", null)
                        .WithMany("Boards")
                        .HasForeignKey("PanelDbModelId");
                });

            modelBuilder.Entity("Infrastructure.Data.Defects.DefectDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.OperationTasks.OperationTaskDbModel", null)
                        .WithMany("Defects")
                        .HasForeignKey("OperationTaskDbModelId");
                });

            modelBuilder.Entity("Infrastructure.Data.OperationTasks.OperationTaskDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Logfiles.LogfileDbModel", "Logfile")
                        .WithMany()
                        .HasForeignKey("LogfileId");

                    b.HasOne("Infrastructure.Data.Operations.OperationDbModel", null)
                        .WithMany("Tasks")
                        .HasForeignKey("OperationDbModelId");

                    b.Navigation("Logfile");
                });

            modelBuilder.Entity("Infrastructure.Data.Operations.OperationDbModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Panels.PanelDbModel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Infrastructure.Data.OperationTasks.OperationTaskDbModel", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Infrastructure.Data.Operations.OperationDbModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Infrastructure.Data.Panels.PanelDbModel", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
